//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuiz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.tblQuestionAnswers = new HashSet<QuestionAnswer>();
            this.tblQuestionTags = new HashSet<QuestionTag>();
            this.tblQuizPassQuestions = new HashSet<QuizPassQuestion>();
            this.tblQuizQuestions = new HashSet<QuizQuestion>();
        }
    
        public int Id { get; set; }
        public int QuestionTypeId { get; set; }
        public int TopicId { get; set; }
        public string QuestionText { get; set; }
        public byte QuestionComplexity { get; set; }
        public bool IsActive { get; set; }
    
        public virtual QuestionType tblQuestionType { get; set; }
        public virtual Topic tblTopic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionAnswer> tblQuestionAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionTag> tblQuestionTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizPassQuestion> tblQuizPassQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizQuestion> tblQuizQuestions { get; set; }
    }
}
